name: COBOL Test with DB2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

env:
  COB_LIBRARY_PATH: /home/runner/work/poe-cobol-project/poe-cobol-project
  COB_FILE_PATH: /home/runner/work/poe-cobol-project/poe-cobol-project

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
          - operating-system: ubuntu-latest
            python-version: '3.6'
            label: linux-64-py-3-6
            prefix: /usr/share/miniconda3/envs/my-env
    steps:
    - uses: actions/checkout@v2
    - name: Install COBOL compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gnucobol
        echo "sudo apt-get install -y libsqlite3-dev"
    - name: Get amalgamation source code SQLITE
      run: |
        echo "mkdir sqlite_folder"
        echo "tar -xvf ./sqlite/sqlite-snapshot.tar.gz -C sqlite_folder --strip-components 1"
        echo "cp ./sqlite_folder/sqlite3.c ./sqlite3.c"
    - name: Initialize database from .tests/SQL.txt
      run: |
        echo "sqlite3 DBMAJCPT.db < ./SQL/SQL-GEN.sql"
    - name: compil - GKCTRL01
      run: cobc -m -fdebugging-line GKCTRL01.cob
    - name: compil - TSTTRL01
      run: |
        cobc -x -o TSTTRL01 ./tests/TSTTRL01.cob GKCTRL01.so
    - name: Compile the C code SQLITE
      run: |
        echo "cobc -c -lsqlit3 sqlite3.c"
    - name: compil - PGM
      run: |
        echo "cobc -x -o PGM ./tests/PGM.cob GKCTRL01.so -lsqlite3"
    - name: precompilation MAXXXs - ignoring SQL CALLS
      run: |
        python ./workflows/precompiler.py ./accessors/MACPT.cob MACPT.cob
        python ./workflows/precompiler.py ./accessors/MAHIS.cob MAHIS.cob
        python ./workflows/precompiler.py ./accessors/MADEV.cob MADEV.cob
        python ./workflows/precompiler.py ./accessors/MAOPE.cob MAOPE.cob
    - name: See precompile code
      run: echo "$(cat PC-MACPT.cob)"
    - name: compil - MAXXXs
      run: |
        cobc -m -fdebugging-line MACPT.cob
        cobc -m -fdebugging-line MAHIS.cob
        cobc -m -fdebugging-line MADEV.cob
        cobc -m -fdebugging-line MAOPE.cob
    - name: compile - TSTMAJ01
      run: |
        cobc -x -o TSTMAJ01 ./tests/TSTMAJ01.cob MACPT.so MAHIS.so MADEV.so MAOPE.so
    - name: Ls
      run: ls
    - name: Env
      run: cobcrun --runtime-config
    - name: Compiler info
      run: cobc --info
    - name: Run tests - GKCTRL01
      run: |
        ./TSTTRL01
        if [[ $? -eq 0 ]]; then
          echo "Tests Succeed"
          exit 0
        fi
    - name: Run tests - GKMAJ001
      run: |
        ./TSTMAJ01
        if [[ $? -eq 0 ]]; then
          echo "Tests Succeed"
          exit 0
        fi