name: COBOL Test with DB2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

env:
  COB_LIBRARY_PATH: /home/runner/work/poe-cobol-project/poe-cobol-project
  COB_FILE_PATH: /home/runner/work/poe-cobol-project/poe-cobol-project

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install COBOL compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gnucobol libsqlite3-dev
    - name: Get amalgamation source code SQLITE
      run: |
        mkdir sqlite_folder
        tar -xvf ./sqlite/sqlite-snapshot.tar.gz -C sqlite_folder --strip-components 1
        cp ./sqlite_folder/sqlite3.c ./sqlite3.c
    - name: Initialize database from .tests/SQL.txt
      run: |
        echo "DUMMY - Initialize DB..."
    - name: Compile the C code SQLITE
      run: |
        cobc -c -lsqlit3 sqlite3.c
    - name: compil - GKCTRL01
      run: cobc -m -fdebugging-line GKCTRL01.cob
    - name: compil - TSTTRL01
      run: |
        cobc -x -o TSTTRL01 ./tests/TSTTRL01.cob GKCTRL01.so
    - name: Ls
      run: ls
    - name: Env
      run: cobcrun --runtime-config
    - name: Compiler info
      run: cobc --info
    - name: Run tests
      run: |
        ./TSTTRL01
        if [[ $? -eq 0 ]]; then
          echo "Tests Succeed"
          exit 0
        fi